# Generated by Django 2.0.7 on 2020-03-31 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hiringapp.utils
import oauth2client.contrib.django_util.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('feedback', 'Feedback')], default=hiringapp.utils.EmailType('invitation'), max_length=100, unique=True)),
                ('mail_subject', models.CharField(max_length=100)),
                ('mail_content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('activity_duration', models.TimeField()),
                ('activity_start_time', models.DateTimeField(blank=True, null=True)),
                ('activity_drive_link', models.URLField(max_length=500)),
                ('activity_uuid', models.UUIDField(default=uuid.UUID('411517f3-6c2b-4fc2-a530-8eba6a70761f'), primary_key=True, serialize=False)),
                ('activity_solution_link', models.URLField(blank=True, max_length=500, null=True)),
                ('activity_status', models.CharField(choices=[(hiringapp.utils.ActivityStatus('started'), 'started'), (hiringapp.utils.ActivityStatus('submitted'), 'submitted'), (hiringapp.utils.ActivityStatus('not_yet_started'), 'not_yet_started'), (hiringapp.utils.ActivityStatus('expired'), 'expired')], default=hiringapp.utils.ActivityStatus('not_yet_started'), max_length=500)),
                ('reminder_for_submission_time', models.TimeField()),
                ('invitation_creation_dateandtime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('invitation_host', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
