# Generated by Django 2.2.11 on 2020-03-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('activity_duration', models.TimeField()),
                ('activity_start_time', models.DateTimeField(blank=True, null=True)),
                ('activity_drive_link', models.URLField(max_length=500)),
                ('activity_start_link', models.URLField(blank=True, max_length=500, null=True)),
                ('activity_solution_link', models.URLField(blank=True, max_length=500, null=True)),
                ('reminder_for_submission_time', models.TimeField()),
            ],
        ),
    ]
