# Generated by Django 2.0.7 on 2020-04-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hiringapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsmodel',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_status',
            field=models.CharField(choices=[('not_yet_started', 'Not_Yet_Started'), ('started', 'Started'), ('submitted', 'Submitted'), ('expired', 'Expired')], default=hiringapp.utils.ActivityStatus('not_yet_started'), max_length=500),
        ),
    ]
