# Generated by Django 2.0.7 on 2020-04-14 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
