# Generated by Django 2.0.7 on 2020-04-17 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiringapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="activity_drive_link",
            field=models.URLField(
                help_text="Under the file menu in google doc click Publish to the web"
                + "and copy the iframe link and paste here.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="activity_duration",
            field=models.DurationField(
                default=datetime.timedelta(days=2),
                help_text="Use the following format DD HH:MM:SS ",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="activity_status",
            field=models.CharField(
                choices=[
                    ("not_yet_started", "NOT_YET_STARTED"),
                    ("started", "STARTED"),
                    ("submitted", "SUBMITTED"),
                    ("expired", "EXPIRED"),
                ],
                default="not_yet_started",
                editable=False,
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="candidate_email",
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name="submission",
            name="candidate_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="submission",
            name="reminder_for_submission_time",
            field=models.DurationField(
                default=datetime.timedelta(seconds=7200),
                help_text="Candidate will be reminded to submit the solution when this much time is left."
                + "Enter the time in HH:MM:SS format",
            ),
        ),
    ]
