# Generated by Django 2.2.11 on 2020-03-26 07:07

from django.db import migrations, models
import hiringapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0002_submission_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='text',
        ),
        migrations.AddField(
            model_name='submission',
            name='activity_status',
            field=models.CharField(choices=[(hiringapp.utils.ActivityStatus('started'), 'started'), (hiringapp.utils.ActivityStatus('submitted'), 'submitted'), (hiringapp.utils.ActivityStatus('not_yet_started'), 'not_yet_started'), (hiringapp.utils.ActivityStatus('expired'), 'expired')], default=hiringapp.utils.ActivityStatus('not_yet_started'), max_length=500),
        ),
    ]
