# Generated by Django 2.0.7 on 2020-04-08 13:25

from django.db import migrations, models
import hiringapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0002_auto_20200407_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='mail_type',
            field=models.CharField(choices=[('INVITATION', 'invitation'), ('REMINDER', 'reminder'), ('ACTIVITYEXPIRED', 'activity_expired'), ('ACTIVITYSOLUTION', 'activity_solution'), ('SUBMISSIONREMINDER', 'reminder_to_submit')], default=hiringapp.utils.EmailType('invitation'), max_length=100, unique=True),
        ),
    ]
