# Generated by Django 2.2.11 on 2020-03-26 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0003_auto_20200326_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='activity_start_link',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='id',
        ),
        migrations.AddField(
            model_name='submission',
            name='activity_invite_link',
            field=models.UUIDField(default=uuid.UUID('ab9bda6b-dea0-44bf-b5f4-f1dc3afd6377'), editable=False, primary_key=True, serialize=False),
        ),
    ]
