# Generated by Django 2.0.7 on 2020-04-08 19:27

from django.db import migrations, models
import hiringapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0003_auto_20200408_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='mail_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('activity_expired', 'ActivityExpired'), ('activity_solution', 'ActivitySolution'), ('reminder_to_submit', 'SubmissionReminder')], default=hiringapp.utils.EmailType('invitation'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_status',
            field=models.CharField(choices=[('not_yet_started', 'Not_Yet_Started'), ('started', 'Started'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='not_yet_started', max_length=500),
        ),
    ]
