# Generated by Django 2.0.7 on 2020-04-08 19:27

from django.db import migrations, models
import hiringapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0003_auto_20200408_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='mail_type',
            field=models.CharField(choices=[('invitation', 'INVITATION'), ('reminder', 'REMINDER'), ('activity_expired', 'ACTIVITYEXPIRED'), ('activity_solution', 'ACTIVITYSOLUTION'), ('reminder_to_submit', 'SUBMISSIONREMINDER')], default=hiringapp.utils.EmailType('invitation'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_status',
            field=models.CharField(choices=[('not_yet_started', 'NOTYETSTARTED'), ('started', 'STARTED'), ('submitted', 'SUBMITTED'), ('expired', 'EXPIRED')], default='not_yet_started', max_length=500),
        ),
    ]
