# Generated by Django 2.0.7 on 2020-04-01 04:54

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0003_auto_20200401_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='activity_time',
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_duration',
            field=models.DurationField(default=datetime.timedelta(days=2)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid',
            field=models.UUIDField(default=uuid.UUID('f7acb316-d668-49c4-a57d-df6a774f854b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reminder_for_submission_time',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
