# Generated by Django 2.0.7 on 2020-04-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0004_auto_20200408_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='id',
        ),
        migrations.DeleteModel(
            name='MailModel',
        ),
        migrations.DeleteModel(
            name='MailSummary',
        ),
        migrations.DeleteModel(
            name='CredentialsModel',
        ),
    ]
