# Generated by Django 2.0.7 on 2020-03-26 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0004_auto_20200326_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='activity_invite_link',
            field=models.UUIDField(default=uuid.UUID('83a5b357-c580-426a-8be5-ca308e9abd26'), primary_key=True, serialize=False),
        ),
    ]
