# Generated by Django 2.0.7 on 2020-04-01 10:04

from django.db import migrations, models
import hiringapp.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0004_auto_20200401_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('feedback', 'Feedback')], default=hiringapp.utils.EmailType('invitation'), max_length=100, unique=True)),
                ('activity_uuid', models.UUIDField(null=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('date_of_mail', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid',
            field=models.UUIDField(default=uuid.UUID('6cea59da-c05f-4045-8687-19b1549a30b0'), primary_key=True, serialize=False),
        ),
    ]
