# Generated by Django 2.0.7 on 2020-03-26 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('hiringapp', '0005_auto_20200326_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_invite_link',
            field=models.UUIDField(default=uuid.UUID('73c704ad-946c-41a0-a9eb-2ecdaeaae2a8'), primary_key=True, serialize=False),
        ),
    ]
