# Generated by Django 2.0.7 on 2020-04-01 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0005_auto_20200401_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsummary',
            name='date_of_mail',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid',
            field=models.UUIDField(default=uuid.UUID('a636fb48-9140-4d28-93ac-6aaa74730b35'), primary_key=True, serialize=False),
        ),
    ]
