# Generated by Django 2.0.7 on 2020-04-01 12:17

from django.db import migrations, models
import hiringapp.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0006_auto_20200401_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsummary',
            name='mail_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('feedback', 'Feedback')], default=hiringapp.utils.EmailType('invitation'), max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid',
            field=models.UUIDField(default=uuid.UUID('f60c8ff7-deaf-4528-95c8-e982ebe46d32'), primary_key=True, serialize=False),
        ),
    ]
