# Generated by Django 2.0.7 on 2020-04-02 14:53

from django.db import migrations, models
import hiringapp.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0007_auto_20200401_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='mail_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('feedback', 'Feedback'), ('reminder_to_submit', 'SubmissionReminder')], default=hiringapp.utils.EmailType('invitation'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mailsummary',
            name='mail_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('feedback', 'Feedback'), ('reminder_to_submit', 'SubmissionReminder')], default=hiringapp.utils.EmailType('invitation'), max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
