# Generated by Django 2.0.7 on 2020-04-06 00:17

from django.db import migrations, models
import hiringapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0008_auto_20200402_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='mail_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('activity_expired', 'ActivityExpired'), ('activity_solution', 'ActivitySolution'), ('reminder_to_submit', 'SubmissionReminder')], default=hiringapp.utils.EmailType('invitation'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mailsummary',
            name='mail_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('activity_expired', 'ActivityExpired'), ('activity_solution', 'ActivitySolution'), ('reminder_to_submit', 'SubmissionReminder')], default=hiringapp.utils.EmailType('invitation'), max_length=100),
        ),
    ]
