# Generated by Django 2.0.7 on 2020-03-30 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0010_auto_20200330_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid_link',
            field=models.UUIDField(default=uuid.UUID('4bf2e28b-333b-43cb-8b72-c7cf6e3e6b6c'), primary_key=True, serialize=False),
        ),
    ]
