# Generated by Django 2.0.7 on 2020-03-30 10:08

from django.db import migrations, models
import hiringapp.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0011_auto_20200330_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='mail_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('reminder', 'Reminder'), ('feedback', 'Feedback')], default=hiringapp.utils.EmailType('invitation'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid_link',
            field=models.UUIDField(default=uuid.UUID('70f98d0f-d2ac-4890-8a6c-7580afbbae77'), primary_key=True, serialize=False),
        ),
    ]
