# Generated by Django 2.0.7 on 2020-03-31 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0012_auto_20200330_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='invitation_creation_dateandtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid_link',
            field=models.UUIDField(default=uuid.UUID('7885fc44-d0c7-45fd-beb0-325f1bd1f265'), primary_key=True, serialize=False),
        ),
    ]
