# Generated by Django 2.0.7 on 2020-03-31 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0013_auto_20200331_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid_link',
            field=models.UUIDField(default=uuid.UUID('df773be2-8c0a-41a8-9185-c536ef6e0fdc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='invitation_creation_dateandtime',
            field=models.DateTimeField(editable=False),
        ),
    ]
