# Generated by Django 2.0.7 on 2020-03-31 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0014_auto_20200331_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid_link',
            field=models.UUIDField(default=uuid.UUID('f5dd8be8-232c-4254-8316-b7e3cfe26984'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='invitation_creation_dateandtime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
