# Generated by Django 2.0.7 on 2020-03-31 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiringapp', '0015_auto_20200331_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='invitation_host',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid_link',
            field=models.UUIDField(default=uuid.UUID('5ea36348-f209-4e33-8f73-c62abd99c52e'), primary_key=True, serialize=False),
        ),
    ]
