# Generated by Django 2.0.7 on 2020-03-31 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0020_auto_20200331_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='mail_subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid_link',
            field=models.UUIDField(default=uuid.UUID('b4f440b3-297b-45ba-8c14-88c25c8991fb'), primary_key=True, serialize=False),
        ),
    ]
