# Generated by Django 2.0.7 on 2020-03-31 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiringapp', '0022_auto_20200331_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='activity_uuid',
            field=models.UUIDField(default=uuid.UUID('e24860e9-9c40-4af6-91d1-1dc6be6c0342'), primary_key=True, serialize=False),
        ),
    ]
