# Generated by Django 2.0.7 on 2020-04-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailingapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="mail_status",
            field=models.CharField(
                choices=[("sent", "SENT"), ("not_sent", "NOT_SENT")],
                default="not_sent",
                max_length=10,
            ),
        ),
    ]
