# Generated by Django 2.0.7 on 2020-04-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailSummary',
            new_name='EmailLog',
        ),
    ]
