# Generated by Django 2.0.7 on 2020-04-20 11:00

from django.db import migrations, models
import mailingapp.constants


class Migration(migrations.Migration):

    dependencies = [
        ("mailingapp", "0002_auto_20200420_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="mail_status",
            field=models.CharField(
                choices=[("sent", "SENT"), ("not_sent", "NOT_SENT")],
                default=mailingapp.constants.EmailStatus("not_sent"),
                max_length=100,
            ),
        ),
    ]
