# Generated by Django 2.0.7 on 2020-04-17 14:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("candidate_name", models.CharField(max_length=50)),
                ("candidate_email", models.EmailField(max_length=70)),
                (
                    "activity_duration",
                    models.DurationField(
                        default=datetime.timedelta(days=2),
                        help_text="Use the following format DD HH:MM:SS ",
                    ),
                ),
                (
                    "activity_start_time",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "activity_drive_link",
                    models.URLField(
                        help_text=(
                            "Under the file menu in google doc click Publish to the web and"
                            "copy the iframe link and paste here."
                        ),
                        max_length=500,
                    ),
                ),
                (
                    "activity_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_solution_link",
                    models.URLField(
                        blank=True, editable=False, max_length=500, null=True
                    ),
                ),
                (
                    "activity_status",
                    models.CharField(
                        choices=[
                            ("not_yet_started", "NOT_YET_STARTED"),
                            ("started", "STARTED"),
                            ("submitted", "SUBMITTED"),
                            ("expired", "EXPIRED"),
                        ],
                        default="not_yet_started",
                        editable=False,
                        max_length=500,
                    ),
                ),
                (
                    "reminder_for_submission_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=7200),
                        help_text="Candidate will be reminded to submit when this much time is left."
                        "Enter the time in HH:MM:SS format",
                    ),
                ),
                (
                    "invitation_creation_dateandtime",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "invitation_host",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
