# Generated by Django 2.0.7 on 2020-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activitylauncher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="activity_drive_link",
            field=models.URLField(
                help_text="Under the file menu in google doc click Publish to the web and "
                + "copy the iframe link and paste here.",
                max_length=500,
            ),
        ),
    ]
