# Generated by Django 2.0.7 on 2020-04-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activitylauncher", "0002_auto_20200424_1204"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="activity_host",
            new_name="invitation_host",
        ),
    ]
